CREATE TABLE dbo.WineTag
(
    WineTagId INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_WineTag_Id PRIMARY KEY CLUSTERED,
    TagId INT NOT NULL,
    WineId INT NOT NULL,
    CONSTRAINT FK_WineTag_Tag FOREIGN KEY (TagId) REFERENCES dbo.Tag(TagId),
    CONSTRAINT FK_WineTag_Wine FOREIGN KEY (WineId) REFERENCES dbo.Wine(WineId)
)

GO
